{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "937c056a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: flask-session in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.4.0)\n",
      "Requirement already satisfied: cachelib in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from flask-session) (0.9.0)\n",
      "Requirement already satisfied: Flask>=0.8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from flask-session) (2.2.2)\n",
      "Requirement already satisfied: click>=8.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from Flask>=0.8->flask-session) (8.1.3)\n",
      "Requirement already satisfied: Werkzeug>=2.2.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from Flask>=0.8->flask-session) (2.2.2)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from Flask>=0.8->flask-session) (2.1.2)\n",
      "Requirement already satisfied: Jinja2>=3.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from Flask>=0.8->flask-session) (3.1.2)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from Jinja2>=3.0->Flask>=0.8->flask-session) (2.1.1)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/utils/logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/console.py\", line 1673, in print\n",
      "    extend(render(renderable, render_options))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/console.py\", line 1305, in render\n",
      "    for render_output in iter_render:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/utils/logging.py\", line 134, in __rich_console__\n",
      "    for line in lines:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/segment.py\", line 249, in split_lines\n",
      "    for segment in segments:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/console.py\", line 1283, in render\n",
      "    renderable = rich_cast(renderable)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/rich/protocol.py\", line 36, in rich_cast\n",
      "    renderable = cast_method()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py\", line 130, in __rich__\n",
      "    pip_cmd = get_best_invocation_for_this_pip()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/utils/entrypoints.py\", line 58, in get_best_invocation_for_this_pip\n",
      "    if found_executable and os.path.samefile(\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/genericpath.py\", line 101, in samefile\n",
      "    s2 = os.stat(f2)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.10/bin/pip'\n",
      "Call stack:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/bin/pip3\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/cli/main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/cli/base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n",
      "    self.handle_pip_version_check(options)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/cli/req_command.py\", line 190, in handle_pip_version_check\n",
      "    pip_self_version_check(session, options)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py\", line 236, in pip_self_version_check\n",
      "    logger.warning(\"[present-rich] %s\", upgrade_prompt)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py\", line 1489, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_internal/utils/logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: '[present-rich] %s'\n",
      "Arguments: (UpgradePrompt(old='22.2.2', new='22.3.1'),)\n"
     ]
    }
   ],
   "source": [
    "!pip3 install flask-session"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a0a051b2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: werkzeug==2.0.3 in /Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages (2.0.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install werkzeug==2.0.3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "70011912",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Database successfully created.\n"
     ]
    }
   ],
   "source": [
    "################################################################################################################\n",
    "\n",
    "# EXTERNAL MODULES TO BE USED\n",
    "\n",
    "################################################################################################################\n",
    "import os\n",
    "import secrets\n",
    "from PIL import Image\n",
    "from flask import Flask, flash, render_template, request, redirect, url_for, session\n",
    "from flask_session import Session\n",
    "from flask_bcrypt import Bcrypt\n",
    "from functools import wraps\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "from flask_login import LoginManager\n",
    "login_manager = LoginManager()\n",
    "login_manager.login_view = 'login'\n",
    "\n",
    "app = Flask(__name__)\n",
    "bcrypt = Bcrypt(app)\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# APP CONFIGURATION\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:root@localhost/workshop'\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///cdgallery.db'\n",
    "app.config['SESSION_TYPE'] = 'filesystem'\n",
    "app.config['SECRET_KEY'] = 'thisismysecret'\n",
    "app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False\n",
    "Session(app)\n",
    "\n",
    "UPLOAD_FOLDER = 'static/profile_pics'\n",
    "app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER\n",
    "app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024\n",
    "ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])\n",
    "\n",
    "@login_manager.user_loader\n",
    "def load_user(user_id):\n",
    "    return User.get(user_id)\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# SELF-DEFINED LOGIN MANAGER DECORATOR\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "def login_required(func):\n",
    "    @wraps(func)\n",
    "    def wrap(*args, **kwargs):\n",
    "        if 'logged_in' in session:\n",
    "            return func(*args, **kwargs)\n",
    "        else:\n",
    "            flash('请先进行登陆','danger')\n",
    "            \n",
    "            login_url = '%s?next=%s' % (url_for('login'), next_url)\n",
    "            return redirect(login_url)\n",
    "    return wrap\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# DATA MODELS\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "db = SQLAlchemy(app)\n",
    "\n",
    "class Blog(db.Model):\n",
    "    __tablename__ = 'blogs'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    title = db.Column(db.String(255))\n",
    "    body = db.Column(db.Text, nullable=False)\n",
    "    author = db.Column(db.String(255))\n",
    "    post_date = db.Column(db.TIMESTAMP, default=datetime.utcnow, nullable=False)\n",
    "    views = db.Column(db.Integer,default=0)\n",
    "    comments = db.Column(db.Integer,default=0)\n",
    "\n",
    "class User(db.Model):\n",
    "    __tablename__ = 'users'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    username = db.Column(db.String(50))\n",
    "    email = db.Column(db.String(255))\n",
    "    password = db.Column(db.String(80))\n",
    "    bio = db.Column(db.Text, nullable=False)\n",
    "    admin = db.Column(db.Boolean)\n",
    "    image_file = db.Column(db.String(255), nullable=False, default='default.jpg')\n",
    "    active = db.Column(db.Boolean)\n",
    "\n",
    "class Comment(db.Model):\n",
    "    __tablename__ = 'comments'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    name = db.Column(db.String(200), unique=False, nullable=False)\n",
    "    message = db.Column(db.Text, nullable=False)\n",
    "    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id', ondelete='CASCADE'), nullable=False)\n",
    "    blog = db.relationship('Blog', backref=db.backref('blogs',lazy=True, passive_deletes=True))\n",
    "    date_pub = db.Column(db.TIMESTAMP, nullable=False, default=datetime.utcnow)   \n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# WEB ROUTES FOR CONTROLLING ACCESS TO TEMPLATE VIEWS\n",
    "\n",
    "################################################################################################################\n",
    "try:\n",
    "    db.create_all()\n",
    "    print(\"Database successfully created.\")\n",
    "except Exception as e:\n",
    "    print(\"Exception occurred.\",e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6027b5ab",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Database successfully created.\n"
     ]
    }
   ],
   "source": [
    "################################################################################################################\n",
    "\n",
    "# EXTERNAL MODULES TO BE USED\n",
    "\n",
    "################################################################################################################\n",
    "import os\n",
    "import secrets\n",
    "from PIL import Image\n",
    "from flask import Flask, flash, render_template, request, redirect, url_for, session\n",
    "from flask_session.__init__ import Session\n",
    "from flask_bcrypt import Bcrypt\n",
    "from functools import wraps\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "from flask_login import LoginManager\n",
    "login_manager = LoginManager()\n",
    "login_manager.login_view = 'login'\n",
    "\n",
    "app = Flask(__name__)\n",
    "bcrypt = Bcrypt(app)\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# APP CONFIGURATION\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:root@localhost/workshop'\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///exhibition.db'\n",
    "app.config['SESSION_TYPE'] = 'filesystem'\n",
    "app.config['SECRET_KEY'] = 'thisismysecret'\n",
    "app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False\n",
    "Session(app)\n",
    "\n",
    "UPLOAD_FOLDER = 'static/profile_pics'\n",
    "app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER\n",
    "app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024\n",
    "ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])\n",
    "\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# DATA MODELS\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "db = SQLAlchemy(app)\n",
    "\n",
    "class exhibition(db.Model):\n",
    "    __tablename__ = 'exhibitions'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    title = db.Column(db.String(255))\n",
    "    date = db.Column(db.String(255))\n",
    "    palce = db.Column(db.String(255))\n",
    "    body = db.Column(db.Text, nullable=False)\n",
    "    author = db.Column(db.String(255))\n",
    "      \n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# WEB ROUTES FOR CONTROLLING ACCESS TO TEMPLATE VIEWS\n",
    "\n",
    "################################################################################################################\n",
    "try:\n",
    "    db.create_all()\n",
    "    print(\"Database successfully created.\")\n",
    "except Exception as e:\n",
    "    print(\"Exception occurred.\",e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7110b2d8",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Database successfully created.\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      " * Restarting with watchdog (fsevents)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
      "    app.initialize(argv)\n",
      "  File \"/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py\", line 88, in inner\n",
      "    return method(app, *args, **kwargs)\n",
      "  File \"/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 632, in initialize\n",
      "    self.init_sockets()\n",
      "  File \"/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 282, in init_sockets\n",
      "    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)\n",
      "  File \"/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 229, in _bind_socket\n",
      "    return self._try_bind_socket(s, port)\n",
      "  File \"/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 205, in _try_bind_socket\n",
      "    s.bind(\"tcp://%s:%i\" % (self.ip, port))\n",
      "  File \"/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/zmq/sugar/socket.py\", line 214, in bind\n",
      "    super().bind(addr)\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 540, in zmq.backend.cython.socket.Socket.bind\n",
      "  File \"zmq/backend/cython/checkrc.pxd\", line 28, in zmq.backend.cython.checkrc._check_rc\n",
      "zmq.error.ZMQError: Address already in use\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "1",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[0;31mSystemExit\u001b[0m\u001b[0;31m:\u001b[0m 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zhongyiming/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3377: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    " ################################################################################################################\n",
    "\n",
    "# EXTERNAL MODULES TO BE USED\n",
    "\n",
    "################################################################################################################\n",
    "import os\n",
    "import secrets\n",
    "from PIL import Image\n",
    "from flask import Flask, flash, render_template, request, redirect, url_for, session\n",
    "from flask_session.__init__ import Session\n",
    "from flask_bcrypt import Bcrypt\n",
    "from functools import wraps\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "from flask_login import LoginManager\n",
    "login_manager = LoginManager()\n",
    "\n",
    "app = Flask(__name__)\n",
    "bcrypt = Bcrypt(app)\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# APP CONFIGURATION\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:root@localhost/workshop'\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///cdgallery.db'\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///cdgallery.db'\n",
    "app.config['SESSION_TYPE'] = 'filesystem'\n",
    "app.config['SECRET_KEY'] = 'thisismysecret'\n",
    "app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False\n",
    "Session(app)\n",
    "\n",
    "UPLOAD_FOLDER = 'static/profile_pics'\n",
    "app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER\n",
    "app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024\n",
    "ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])\n",
    "\n",
    "@login_manager.user_loader\n",
    "def load_user(user_id):\n",
    "    return User.get(user_id)\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# SELF-DEFINED LOGIN MANAGER DECORATOR\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "def login_required(func):\n",
    "    @wraps(func)\n",
    "    def wrap(*args, **kwargs):\n",
    "        if 'logged_in' in session:\n",
    "            return func(*args, **kwargs)\n",
    "        else:\n",
    "            flash('You need to login first.','danger')\n",
    "            return redirect(url_for('login'))\n",
    "    return wrap\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# DATA MODELS\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "db = SQLAlchemy(app)\n",
    "\n",
    "class Blog(db.Model):\n",
    "    __tablename__ = 'blogs'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    title = db.Column(db.String(255))\n",
    "    body = db.Column(db.Text, nullable=False)\n",
    "    author = db.Column(db.String(255))\n",
    "    post_date = db.Column(db.TIMESTAMP, default=datetime.utcnow, nullable=False)\n",
    "    views = db.Column(db.Integer,default=0)\n",
    "    comments = db.Column(db.Integer,default=0)\n",
    "\n",
    "class User(db.Model):\n",
    "    __tablename__ = 'users'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    username = db.Column(db.String(50))\n",
    "    email = db.Column(db.String(255))\n",
    "    password = db.Column(db.String(80))\n",
    "    bio = db.Column(db.Text, nullable=False)\n",
    "    admin = db.Column(db.Boolean)\n",
    "    image_file = db.Column(db.String(255), nullable=False, default='default.jpg')\n",
    "    active = db.Column(db.Boolean)\n",
    "\n",
    "class Comment(db.Model):\n",
    "    __tablename__ = 'comments'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    name = db.Column(db.String(200), unique=False, nullable=False)\n",
    "    message = db.Column(db.Text, nullable=False)\n",
    "    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id', ondelete='CASCADE'), nullable=False)\n",
    "    blog = db.relationship('Blog', backref=db.backref('blogs',lazy=True, passive_deletes=True))\n",
    "    date_pub = db.Column(db.TIMESTAMP, nullable=False, default=datetime.utcnow)  \n",
    "    \n",
    "class Exhibition(db.Model):\n",
    "    __tablename__ = 'exhibitions'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    title = db.Column(db.Text)\n",
    "    start = db.Column(db.Integer)\n",
    "    end = db.Column(db.Integer)\n",
    "    date = db.Column(db.Text)\n",
    "    datemore = db.Column(db.Text)\n",
    "    gallery = db.Column(db.Text)\n",
    "    maps = db.Column(db.Text)\n",
    "    place = db.Column(db.Text)\n",
    "    brief = db.Column(db.Text)\n",
    "    body = db.Column(db.Text)\n",
    "    introimg = db.Column(db.Text)\n",
    "    images = db.Column(db.Text)\n",
    "    district = db.Column(db.Text)\n",
    "    buy = db.Column(db.Text) \n",
    "    maplink = db.Column(db.Text) \n",
    "    \n",
    "\n",
    "class Gallery(db.Model):\n",
    "    __tablename__ = 'galleries'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    name = db.Column(db.Text)\n",
    "    maps = db.Column(db.Text)\n",
    "    time = db.Column(db.Text)\n",
    "    body = db.Column(db.Text)\n",
    "    place = db.Column(db.Text)\n",
    "    images = db.Column(db.Text)\n",
    "    maplink = db.Column(db.Text)\n",
    "    \n",
    "class Contribution(db.Model):\n",
    "    __tablename__ = 'contributions'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    title = db.Column(db.String(255))\n",
    "    email = db.Column(db.String(255))\n",
    "    date = db.Column(db.String(255))\n",
    "    place = db.Column(db.String(255))\n",
    "    intro = db.Column(db.String(255))\n",
    "    \n",
    "################################################################################################################\n",
    "\n",
    "# WEB ROUTES FOR CONTROLLING ACCESS TO TEMPLATE VIEWS\n",
    "\n",
    "################################################################################################################\n",
    "try:\n",
    "    db.create_all()\n",
    "    print(\"Database successfully created.\")\n",
    "except Exception as e:\n",
    "    print(\"Exception occurred.\",e)   \n",
    "@app.route(\"/\")\n",
    "def index():\n",
    "    return render_template('index.html')\n",
    "\n",
    "\n",
    "\n",
    "@app.route(\"/exhibitiondistrict\")\n",
    "def exhibitiondistrict():\n",
    "    return render_template('exhibitiondistrict.html')\n",
    "\n",
    "\n",
    "# @app.route(\"/contribution\")\n",
    "# def contribution():\n",
    "#     return render_template('contribution.html')\n",
    "\n",
    "@app.route(\"/membership\")\n",
    "def membership():\n",
    "    return render_template('membership.html')\n",
    "\n",
    "\n",
    "@app.route(\"/exhibitions\")\n",
    "def exhibitions():\n",
    "    page_num = 1\n",
    "    exhibition_list = Exhibition.query.paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "@app.route(\"/exhibitions/<int:page_num>\")\n",
    "def exhibitions_paging(page_num):\n",
    "    exhibition_list = Exhibition.query.paginate(per_page=9, page=page_num, error_out=True) \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "\n",
    "@app.route(\"/galleries\")\n",
    "def galleries():\n",
    "    page_num = 1\n",
    "    gallery_list = Gallery.query.paginate(error_out=True) \n",
    "   \n",
    "    return render_template('galleries.html', galleries=gallery_list)\n",
    "\n",
    "@app.route(\"/gallery_detail/<int:id>\",methods=['GET',\"POST\"])\n",
    "def gallery_detail(id):\n",
    "    dataset = []\n",
    "    gallery = Gallery.query.filter_by(id=id).first()\n",
    "    print(\"gallery.name=\",gallery.name,\"gallery.images=\",gallery.images)\n",
    "    dataset.append({\"name\":gallery.name, \"body\":gallery.body ,\"maplink\":gallery.maplink, \"images\":gallery.images, \"time\":gallery.time, \"place\":gallery.place})\n",
    "    db.session.commit()\n",
    "    \n",
    "    return render_template('gallery_detail.html', galleries=dataset)\n",
    "\n",
    "\n",
    "@app.route(\"/dashboard\")\n",
    "@login_required\n",
    "def dashboard():\n",
    "    page_num = 1\n",
    "    if session['admin'] > 0:\n",
    "        blog_list = Blog.query.paginate(per_page=4, page=page_num, error_out=True) \n",
    "    else:\n",
    "        blog_list = Blog.query.filter_by(author=session['username']).paginate(per_page=4, page=page_num, error_out=True)\n",
    "        \n",
    "    return render_template('dashboard.html', blogs=blog_list)\n",
    "\n",
    "@app.route(\"/dashboard/<int:page_num>\")\n",
    "@login_required\n",
    "def dashboard_paging(page_num):\n",
    "    if session['admin'] > 0:\n",
    "        blog_list = Blog.query.paginate(per_page=4, page=page_num, error_out=True) \n",
    "    else:\n",
    "        blog_list = Blog.query.filter_by(author=session['username']).paginate(per_page=4, page=page_num, error_out=True)\n",
    "        \n",
    "    return render_template('dashboard.html', blogs=blog_list)\n",
    "\n",
    "@app.route('/blogs')\n",
    "#@login_required\n",
    "def blogs():\n",
    "    page_num = 1\n",
    "    blog_list = Blog.query.paginate(per_page=6, page=page_num, error_out=True)\n",
    "    return render_template('blogs.html', blogs=blog_list)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# @app.route(\"/maps\")\n",
    "# def maps(id):\n",
    "#     dataset = []\n",
    "#     exhibition = Exhibition.query.filter_by(id=id).first()\n",
    "#     print(\"exhibition.title=\",exhibition.title,\"exhibition.body=\",exhibition.body)\n",
    "#     dataset.append({\"title\":exhibition.title, \"body\":exhibition.body })\n",
    "#     db.session.commit()\n",
    "#     return render_template('maps.html', exhibitions=dataset)\n",
    "\n",
    "\n",
    "@app.route(\"/blogs/<int:page_num>\")\n",
    "def blogs_paging(page_num):\n",
    "    blog_list = Blog.query.paginate(per_page=6, page=page_num, error_out=True)\n",
    "    return render_template('blogs.html', blogs=blog_list)\n",
    "\n",
    "\n",
    "@app.route('/search')\n",
    "def search():\n",
    "    page_num = 1\n",
    "    keyword = request.args.get('keyword')\n",
    "    print('keyword=',keyword)\n",
    "    if (keyword == ''):\n",
    "         blog_list = Blog.query.paginate(per_page=6, page=page_num, error_out=True) \n",
    "    else:\n",
    "        blog_list = Blog.query.filter(db.or_(Blog.body.contains(keyword),Blog.title.contains(keyword))).paginate(per_page=6, page=page_num, error_out=True)\n",
    "        \n",
    "    return render_template('blogs.html', blogs=blog_list)\n",
    "\n",
    "\n",
    "@app.route('/search2')\n",
    "def search2():\n",
    "    page_num = 1\n",
    "    keyword = request.args.get('keyword')\n",
    "    print('keyword=',keyword)\n",
    "    if (keyword == ''):\n",
    "         exhibition_list = Exhibition.query.paginate(per_page=6, page=page_num, error_out=True) \n",
    "    else:\n",
    "        exhibition_list = Exhibition.query.filter(db.or_(Exhibition.body.contains(keyword),Exhibition.title.contains(keyword))).paginate(per_page=6, page=page_num, error_out=True)\n",
    "        \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "@app.route('/search3')\n",
    "def search3():\n",
    "    page_num = 1\n",
    "    keyword = request.args.get('keyword')\n",
    "    print('keyword=',keyword)\n",
    "    if (keyword == ''):\n",
    "         gallery_list = Gallery.query.paginate(per_page=6, page=page_num, error_out=True) \n",
    "    else:\n",
    "        gallery_list = Gallery.query.filter(db.or_(Gallery.body.contains(keyword),Gallery.name.contains(keyword))).paginate(per_page=6, page=page_num, error_out=True)\n",
    "        \n",
    "    return render_template('galleries.html', galleries=gallery_list)\n",
    "\n",
    "\n",
    "@app.route('/filterjn')\n",
    "def filterjn():\n",
    "    page_num = 1\n",
    "\n",
    "    exhibition_list = Exhibition.query.filter_by(district=\"jn\").paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html',exhibitions=exhibition_list)\n",
    "\n",
    "\n",
    "@app.route('/filterjj')\n",
    "def filterjj():\n",
    "    page_num = 1\n",
    "   \n",
    "    exhibition_list = Exhibition.query.filter_by(district=\"jj\").paginate(per_page=9, page=page_num,error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html',  exhibitions=exhibition_list)\n",
    "\n",
    "@app.route('/filterqy')\n",
    "def filterqy():\n",
    "    page_num = 1\n",
    "   \n",
    "    exhibition_list = Exhibition.query.filter_by(district=\"qy\").paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "@app.route('/filterwh')\n",
    "def filterwh():\n",
    "    page_num = 1\n",
    "   \n",
    "    exhibition_list = Exhibition.query.filter_by(district=\"wh\").paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "\n",
    "@app.route('/filterch')\n",
    "def filterch():\n",
    "    page_num = 1\n",
    "   \n",
    "    exhibition_list = Exhibition.query.filter_by(district=\"ch\").paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "@app.route('/filtergx')\n",
    "def filtergx():\n",
    "    page_num = 1\n",
    "   \n",
    "    exhibition_list = Exhibition.query.filter_by(district=\"gx\").paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "@app.route('/filtertf')\n",
    "def filtertf():\n",
    "    page_num = 1\n",
    "   \n",
    "    exhibition_list = Exhibition.query.filter_by(district=\"tf\").paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "\n",
    "@app.route('/newest')\n",
    "def newest():\n",
    "    page_num = 1\n",
    "    exhibition_list = Exhibition.query.order_by(Exhibition.start.desc()).paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "@app.route('/oldest')\n",
    "def oldest():\n",
    "    page_num = 1\n",
    "    exhibition_list = Exhibition.query.order_by(Exhibition.end).paginate(per_page=9, page=page_num, error_out=True) \n",
    "   \n",
    "    return render_template('exhibitions.html', exhibitions=exhibition_list)\n",
    "\n",
    "\n",
    "@app.route(\"/blog\", methods=[\"GET\",\"POST\"])\n",
    "@login_required\n",
    "def blog():\n",
    "    msg = None\n",
    "    if 'username' in session:\n",
    "        msg = '你好 ' + session['username'] + '！'\n",
    "\n",
    "    if request.method == \"POST\":\n",
    "        title = request.form['title']\n",
    "        body = request.form['body']\n",
    "        author = session['username']\n",
    "        blog = Blog(title=title,body=body,author=author)\n",
    "        db.session.add(blog)\n",
    "        db.session.commit()\n",
    "        msg = \"新动态已发布!\"\n",
    "        print(\"新动态已发布!\")\n",
    "        flash(\"新动态已发布!\")\n",
    "\n",
    "    return render_template('newblog.html', msg = msg)\n",
    "\n",
    "@app.route(\"/blog/<string:id>\", methods=[\"GET\",\"POST\"])\n",
    "@login_required\n",
    "def blogone(id):\n",
    "    dataset = []\n",
    "    if request.method == \"GET\":\n",
    "        msg = \"Edit\"\n",
    "        dataset = []\n",
    "        result = Blog.query.filter_by(id=id).first()\n",
    "\n",
    "    if request.method == \"POST\":\n",
    "        print('blogone update entry ok')\n",
    "        title = request.form['title']\n",
    "        body = request.form['body']\n",
    "        del_flag = request.form['_method']\n",
    "        result = Blog.query.filter_by(id=id).first()\n",
    "        if result is None:\n",
    "            msg = \"好像没有相关内容 换个关键词试试吧!\"\n",
    "            print(\"Not found!\")\n",
    "            return redirect(url_for('blogone'))\n",
    "        else:\n",
    "            if del_flag == 'DELETE':\n",
    "                print(\"Deleted.\")\n",
    "                msg = \"已删除!\"\n",
    "                blog = Blog.query.filter_by(id=id).first()\n",
    "                db.session.delete(blog)\n",
    "                db.session.commit()\n",
    "                return redirect(url_for('profile'))\n",
    "            else:\n",
    "                print(\"Updated\")\n",
    "                msg = \"已更新!\"\n",
    "                blog = Blog.query.filter_by(id=id).first()\n",
    "                blog.title = title\n",
    "                blog.body = body\n",
    "                db.session.commit()\n",
    "\n",
    "    dataset.append(result)\n",
    "    print(dataset)\n",
    "    print(type(dataset))\n",
    "    return render_template('blog.html', entries=dataset, msg=msg, id=id)\n",
    "\n",
    "@app.route(\"/blog_details/<int:id>\",methods=['GET',\"POST\"])\n",
    "def blog_details(id):\n",
    "    user = session.get('user')\n",
    "    msg = None\n",
    "    dataset = []\n",
    "    blog = Blog.query.filter_by(id=id).first()\n",
    "    print(\"blog.views=\",blog.views,\"blog.title=\",blog.title,\"blog.author\", blog.author)\n",
    "    dataset.append({\"title\":blog.title, \"body\":blog.body, \"author\":blog.author, \"post_date\":blog.post_date, \"comments\":blog.comments })\n",
    "    comment = Comment.query.filter_by(blog_id=blog.id).all()\n",
    "    blog.views = blog.views + 1\n",
    "    comment_count = blog.comments\n",
    "    db.session.commit()\n",
    "    Thanks =\"\"\n",
    "    if request.method ==\"POST\":\n",
    "        if 'logged_in' in session:\n",
    "            blog_id = blog.id\n",
    "            name = request.form.get('name')\n",
    "            message = request.form.get('message')\n",
    "            comment = Comment(name=name,message=message,blog_id=blog_id)\n",
    "            db.session.add(comment)\n",
    "            blog.comments = blog.comments + 1\n",
    "            db.session.commit()\n",
    "            msg = \"收到！评论成功\"\n",
    "            flash('收到！', '评论成功')\n",
    "            return redirect(request.url)\n",
    "        else:\n",
    "            session['redirect'] = request.path\n",
    "            return redirect(url_for('login'))\n",
    "\n",
    "    \n",
    "    return render_template('blog_details.html', blogs=dataset, comment=comment, comment_count=comment_count, Thanks=Thanks, msg = msg)\n",
    "\n",
    "\n",
    "\n",
    "# <int:id>\n",
    "\n",
    "@app.route(\"/exhibition_detail/<int:id>\",methods=['GET',\"POST\"])\n",
    "def exhibition_detail(id):\n",
    "    dataset = []\n",
    "    exhibition = Exhibition.query.filter_by(id=id).first()\n",
    "    print(\"exhibition.title=\",exhibition.title,\"exhibition.body=\",exhibition.body, \"exhibition.introimg=\",exhibition.introimg)\n",
    "    dataset.append({\"title\":exhibition.title, \"body\":exhibition.body ,\"maplink\":exhibition.maplink, \"introimg\":exhibition.introimg, \"datemore\":exhibition.datemore, \"place\":exhibition.place})\n",
    "    db.session.commit()\n",
    "    \n",
    "    return render_template('exhibition_detail.html', exhibitions=dataset)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "@app.route(\"/profile/\", defaults={\"username\": \"nobody\"})\n",
    "@app.route(\"/profile/<string:username>\", methods=['GET', 'POST'])\n",
    "@login_required\n",
    "def profile(username):\n",
    "    \n",
    "   \n",
    "    \n",
    "    dataset = []\n",
    "    if request.method == \"GET\":\n",
    "        msg = \"Edit\"\n",
    "        user = User.query.filter_by(username=username).first()\n",
    "#         if user.image_file is None:\n",
    "#             user.image_file = 'default.jpg'\n",
    "#             image_file = url_for('static', filename='profile_pics/' + user.image_file)\n",
    "#         dataset.append({'id':user.id, 'username': user.username,'email': user.email,'bio': user.bio, 'image_file':user.image_file})\n",
    "        \n",
    "    if request.method == \"POST\":\n",
    "        username = request.form['username']\n",
    "        email = request.form['email']\n",
    "        bio = request.form['bio']\n",
    "        id = request.form['id']\n",
    "        user = User.query.filter_by(id=id).first()\n",
    "        user.username = username\n",
    "        user.email = email\n",
    "        user.bio = bio\n",
    "        db.session.commit()\n",
    "        dataset.append({'id':user.id, 'username': user.username,'email': user.email,'bio': user.bio})\n",
    "\n",
    "    page_num = 1\n",
    "    if session['admin'] > 0:\n",
    "        blog_list = Blog.query.paginate(per_page=4, page=page_num, error_out=True) \n",
    "    else:\n",
    "        blog_list = Blog.query.filter_by(author=session['username']).paginate(per_page=4, page=page_num, error_out=True)\n",
    "        \n",
    "    \n",
    "    return render_template('profile.html', entries=dataset, blogs=blog_list)\n",
    "\n",
    "\n",
    "# @app.route(\"/profile/<int:page_num>\")\n",
    "# @login_required\n",
    "# def profile_paging(page_num):\n",
    "#     if session['admin'] > 0:\n",
    "#         blog_list = Blog.query.paginate(per_page=4, page=page_num, error_out=True) \n",
    "#     else:\n",
    "#         blog_list = Blog.query.filter_by(author=session['username']).paginate(per_page=4, page=page_num, error_out=True)\n",
    "        \n",
    "#     return render_template('profile.html', blogs=blog_list)\n",
    "\n",
    "\n",
    "@app.route(\"/login\", methods=[\"GET\",\"POST\"])\n",
    "def login():\n",
    "    msg = None\n",
    "    \n",
    "\n",
    "    if request.method == \"POST\":\n",
    "        username = request.form['username']\n",
    "        password = request.form['password']\n",
    "        user = User.query.filter_by(username=username).first()\n",
    "        \n",
    "        if not user:\n",
    "            print(\"Account does not exist!\")\n",
    "            msg = \"用户不存在\"\n",
    "            flash(\"用户不存在\")\n",
    "            \n",
    "        else:\n",
    "            if bcrypt.check_password_hash(user.password, password):\n",
    "                session['logged_in'] = True\n",
    "                session['username'] = user.username\n",
    "                session['admin'] = user.admin\n",
    "                print(\"Welcome!\")\n",
    "                msg = \"Welcome!\"\n",
    "                res = session.get('redirect')\n",
    "                if res:\n",
    "                    return redirect(res)\n",
    "                return redirect(url_for('profile', username=username))\n",
    "                \n",
    "            msg = \"啊噢 密码错误\"\n",
    "            flash(\"啊噢 密码错误!\")\n",
    "\n",
    "    return render_template('login.html', msg = msg)\n",
    "\n",
    "@app.route(\"/logout\")\n",
    "@login_required\n",
    "def logout():\n",
    "    session.clear()\n",
    "    return render_template('logout.html')\n",
    "\n",
    "\n",
    "@app.route(\"/register\", methods=[\"GET\",\"POST\"])\n",
    "def register():\n",
    "    msg = None\n",
    "    if request.method == \"POST\":\n",
    "        username = request.form['username']\n",
    "        email = request.form['email']\n",
    "        bio = request.form['bio']\n",
    "        password = request.form['password']\n",
    "        password = bcrypt.generate_password_hash(password)\n",
    "        admin = 0\n",
    "        user = User(username=username,email=email,bio=bio,password=password,admin=admin)\n",
    "        db.session.add(user)\n",
    "        db.session.commit()\n",
    "        print(\"You have been registered!\")\n",
    "        msg = \"注册成功 玩得开心！\"\n",
    "        flash(\"注册成功 玩得开心！\")\n",
    "\n",
    "    return render_template('register.html',msg = msg)\n",
    "\n",
    "@app.route(\"/contribution\", methods=[\"GET\",\"POST\"])\n",
    "def contribution():\n",
    "    msg = None\n",
    "    if request.method == \"POST\":\n",
    "        title = request.form['title']\n",
    "        email = request.form['email']\n",
    "        place = request.form['place']\n",
    "        date = request.form['date']\n",
    "        intro = request.form['intro']\n",
    "        admin = 0\n",
    "        contribution = Contribution(title=title,email=email,date=date,place=place,intro=intro)\n",
    "        db.session.add(contribution)\n",
    "        db.session.commit()\n",
    "        print(\"contribution succeed\")\n",
    "        msg = \"收到！感谢你的分享！\"\n",
    "        flash(\"收到！感谢你的分享！\")\n",
    "\n",
    "    return render_template('contribution.html',msg = msg)\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# ERROR HANDLERS\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "@app.errorhandler(404)\n",
    "def page_not_found(e):\n",
    "    return render_template('404.html'), 404\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "# APPLICATION TEST RUN AT PORT 9004\n",
    "\n",
    "################################################################################################################\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)\n",
    "    \n",
    "    %tb"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b7d1e875",
   "metadata": {},
   "source": [
    "##### "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0b2010d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "673efd41",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b82ebe09",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
